# Mopidy 4.0.0a2 + Mopidy-Tidal 0.3.9 + Mopidy-MPD 3.3.0
# Host: wasp.local  |  User: teraflops
# DAC: Topping D90 III SABRE (USB) -> hw:CARD=SABRE,DEV=0
# Salida: ALSA bit-perfect (sin mixer software, sin resampling, sin dither)

[core]
restore_state        = true
max_tracklist_length = 10000

[logging]
verbosity = 1
color     = false

[audio]
output = alsasink device=hw:CARD=SABRE,DEV=0 buffer-time=200000
mixer        = none
mixer_volume =
buffer_time  =

[softwaremixer]
enabled = false

[mpd]
enabled            = true
hostname           = ::
port               = 6600
max_connections    = 20
connection_timeout = 60
zeroconf           = Mopidy MPD on $hostname

[http]
enabled  = true
hostname = ::
port     = 6680

[tidal]
enabled  = true
quality  = HI_RES_LOSSLESS
lazy     = true

[file]
enabled              = true
media_dirs           = /mnt/nas/music|NAS Music
show_dotfiles        = false
follow_symlinks      = false
metadata_timeout     = 1000

[local]
enabled              = true
library              = sqlite
media_dir            = /mnt/nas/music
scan_follow_symlinks = false
scan_timeout         = 2000

[m3u]
enabled = false

[stream]
enabled = false

[tidal_goodies]
enabled = true
